apiVersion: v1
kind: ConfigMap
metadata:
  name: video-processor-config
data:
  MINIO_ENDPOINT: "minio-service:9000"
  MINIO_BUCKET_NAME: "videos"

  RABBITMQ_URL: "amqp://guest:guest@localhost:5672"
  RABBITMQ_CONSUMER_NAME: "video_processing"
  RABBITMQ_PRODUCER_NAME: "db_upload"

  APP_ENV: "prod"
