apiVersion: v1
kind: ConfigMap
metadata:
  name: video-processor-config
data:
  MINIO_HOST: "minio"
  MINIO_PORT: "9000"
  MINIO_BUCKET_NAME: "videos"

  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"

  RABBITMQ_CONSUMER_NAME: "video_processing"
  RABBITMQ_PRODUCER_NAME: "db_upload"

  APP_ENV: "dev"
