apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-deployment
spec:
  selector:
    matchLabels:
      app: video-processor
  template:
    metadata:
      labels:
        app: video-processor
    spec:
      containers:
        - name: video-processor
          image: valery223344/video_processor:0.0.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          # ports:
          # - containerPort: <Port>
