apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-processor-deployment
spec:
  selector:
    matchLabels:
      app: video-processor
  template:
    metadata:
      labels:
        app: video-processor
    spec:
      containers:
        - name: video-processor
          image: valery223344/video_processor:0.0.1
          envFrom:
            - configMapRef:
                name: video-processor-config
            - secretRef:
                name: video-processor-secrets
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
