name: Deploy to Yandex Cloud Kubernetes

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    env:
      REGISTRY: docker.io
      IMAGE_NAME: valery223344/video_processor
      FOLDER_ID: b1gq90lppq2qo7ofbuhb
      CLUSTER_ID: mk8s-cluster

    steps:
      # Шаг 1: Получение кода
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockers/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Configure YC Kubernetes access
        uses: yc-actions/configure-kubernetes@v1
        with:
          k8s-connection: ${{ env.CLUSTER_ID }}
          yc-sa-json-credentials: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/secret.yaml
          kubectl apply -f k8s/deploy.yaml
