name: Deploy to Yandex Cloud Kubernetes

on:
  push:
    branches: [main, develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up project
        uses: VideoHosting-Platform/actions/.github/actions/setup-and-deploy@main
        with:
          registry: 'docker.io'
          image_name: '${{ secrets.DOCKERHUB_USERNAME }}/upload-service'
          folder_id: 'b1gq90lppq2qo7ofbuhb'
          cluster_id: 'mk8s-cluster'
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          yc_service_account_key: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Kubernetes
        run: |
          echo 'RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}' >> .env
          echo 'RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}' >> .env
          echo 'MINIO_ACCESS_KEY=minioadmin' >> .env
          echo 'MINIO_SECRET_KEY=minioadmin' >> .env


          kubectl create secret generic video-processor-secrets --from-env-file=.env --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/configMap.yaml
          kubectl apply -f k8s/deploy.yaml
          kubectl rollout restart -f k8s/deploy.yaml
